### ISSUE TITLE
Avro parsing error StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by gauti251988** [DarioBalinzo/kafka-connect-elasticsearch-source#103]
[ERROR] 2023-11-22 23:05:34,584 [task-thread-ElasticSourceConnectorConnector_1-0] com.github.dariobalinzo.task.ElasticSourceTask poll - error
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
  at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
  at java.base/java.lang.String.charAt(String.java:693)
  at com.github.dariobalinzo.schema.AvroName.filterInvalidCharacters(AvroName.java:30)
  at com.github.dariobalinzo.schema.AvroName.from(AvroName.java:26)
  at com.github.dariobalinzo.schema.SchemaConverter.convert(SchemaConverter.java:40)
  at com.github.dariobalinzo.task.ElasticSourceTask.parseResult(ElasticSourceTask.java:260)
  at com.github.dariobalinzo.task.ElasticSourceTask.poll(ElasticSourceTask.java:207)
  at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:307)
  at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:263)
  at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:200)
  at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:255)
  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.base/java.lang.Thread.run(Thread.java:829)
  

We struggled a lot to get this connector running , now we are facing this error. Looking at code it seems like json key type detection error could not exactly sure which part of the json

**Comment by gauti251988** [comment]
after adding nop in field name converter it worked
