### ISSUE TITLE
Issue using https

### ISSUE THREAD

**Issue by albertwgchu** [DarioBalinzo/kafka-connect-elasticsearch-source#24]
Hi, 

I wrote earlier about adding https support.  I just tried today with version 1.1 and I'm still getting an error.  I looked at the code against https://github.com/inspectorioinc/kafka-connect-elasticsearch-source/ and I didn't see anything obvious.

However I did notice that if I enter an invalid host I get the same error. 

Config:
{
    "connector.class": "com.github.dariobalinzo.ElasticSourceConnector",
    "es.host": "xxx",
    "es.scheme": "https",
    "tasks.max": "1",
    "incrementing.field.name": "@timestamp",
    "connection.attempts": "1",
    "es.port": "9243",
    "mode": "timestamp",
    "topic.prefix": "essource_",
    "es.password": "xxx",
    "name": "essource",
    "es.user": "xxx",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "index.prefix": "test_"
}

Call stack:

[2020-12-21 19:40:29,753] ERROR error in searching index names (com.github.dariobalinzo.elastic.ElasticRepository)
[2020-12-21 19:40:29,753] ERROR [Worker clientId=connect-1, groupId=compose-connect-group] Failed to reconfigure connector's tasks, retrying after backoff: (org.apache.kafka.connect.runtime.distributed.DistributedHerder)
java.lang.RuntimeException: org.elasticsearch.client.ResponseException: method [GET], host [https://xxx:9243], URI [_cat/indices], status line [HTTP/1.1 400 Bad Request]
400 Bad Request
	at com.github.dariobalinzo.elastic.ElasticRepository.catIndices(ElasticRepository.java:106)
	at com.github.dariobalinzo.ElasticSourceConnector.taskConfigs(ElasticSourceConnector.java:98)
	at org.apache.kafka.connect.runtime.Worker.connectorTaskConfigs(Worker.java:373)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.reconfigureConnector(DistributedHerder.java:1420)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.reconfigureConnectorTasksWithRetry(DistributedHerder.java:1358)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1000(DistributedHerder.java:127)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$15$1.call(DistributedHerder.java:1375)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$15$1.call(DistributedHerder.java:1372)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:365)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by DarioBalinzo** [comment]
Hi @albertwgchu ,
I will try to reproduce the error locally with an integration test. 

I've read about a similar issue here https://www.google.com/url?sa=t&source=web&rct=j&url=https://discuss.elastic.co/t/resolved-400-error-responseexception-when-using-example-request-code-for-java-rest-client/98445&ved=2ahUKEwiSlOzs9N_tAhVZPuwKHa3dBLgQFjAAegQIBxAC&usg=AOvVaw32nxEd1oo2s_PGGK2JXc6i
I will check in few days if the issue is similar.

**Comment by albertwgchu** [comment]
@DarioBalinzo Thanks for responding so quickly.  I'll take a look as well, I'm curious why https://github.com/inspectorioinc/kafka-connect-elasticsearch-source works with my instance of ES and not yours.  I should also mention I am using ES 6.8.  

Thanks again.

**Comment by albertwgchu** [comment]
@DarioBalinzo weird, so if I change this it works:

--- a/src/main/java/com/github/dariobalinzo/elastic/ElasticRepository.java
+++ b/src/main/java/com/github/dariobalinzo/elastic/ElasticRepository.java
@@ -100,7 +100,7 @@ public final class ElasticRepository {
         try {
             resp = elasticConnection.getClient()
                     .getLowLevelClient()
-                    .performRequest("GET", "_cat/indices");
+                    .performRequest("GET", "/_cat/indices");
         } catch (IOException e) {
             logger.error("error in searching index names");
             throw new RuntimeException(e);

**Comment by DarioBalinzo** [comment]
Hi @albertwgchu , thanks for sharing the details.
What kind of environment are you using? (local cluster, docker or aws?)

I don't understand your change in the ElasticRepository, it seems identical to me. Can you share the diff or maybe submit a simple PR?


I'm planning to look into this in the next days, but having more info and context will help me in solving this issue.
Thanks

**Comment by albertwgchu** [comment]
Hi @DarioBalinzo,

It's the forward slash before cat.  

.performRequest("GET", "_cat/indices"); // this doesn't work
.performRequest("GET", "/_cat/indices"); // this works

I'm using Docker cp all in one for Kafka and Elastic Cloud for Elastic Search.

Thanks.

**Comment by DarioBalinzo** [comment]
Ok, so it seems similar to this issue https://github.com/elastic/elasticsearch/issues/28923
(If you look to the last answer)

I will put the fix using the correct prefix in version 1.2.
