### ISSUE TITLE
java.lang.NoSuchFieldError: INSTANCE

### ISSUE THREAD

**Issue by sinbadonline** [DarioBalinzo/kafka-connect-elasticsearch-source#34]
When activate this connector with below configuration:
{       
  "name": "global-es-source",
   "config": {
             "connector.class":"com.github.dariobalinzo.ElasticSourceConnector",
             "tasks.max": "1",
             "es.host" : "10.0.129.171;10.0.128.237;10.0.128.64",
             "es.port" : "9200",
             "es.user" : "xxxx",
             "es.password" : "xxxx",
             "es.scheme" : "http",
             "incrementing.field.name" : "@timestamp",
             "topic.prefix" : "global-es-",
             "type.name": "source"
        }
}
And check status of this connector, found below error:
java.lang.NoSuchFieldError: INSTANCE
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.<init>(PoolingNHttpClientConnectionManager.java:591)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.<init>(PoolingNHttpClientConnectionManager.java:163)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.<init>(PoolingNHttpClientConnectionManager.java:147)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.<init>(PoolingNHttpClientConnectionManager.java:119)
	at org.apache.http.impl.nio.client.HttpAsyncClientBuilder.build(HttpAsyncClientBuilder.java:668)
	at org.elasticsearch.client.RestClientBuilder.run(RestClientBuilder.java:218)
	at org.elasticsearch.client.RestClientBuilder.run(RestClientBuilder.java:215)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.elasticsearch.client.RestClientBuilder.createHttpClient(RestClientBuilder.java:215)
	at org.elasticsearch.client.RestClientBuilder.accessbash00(RestClientBuilder.java:42)
	at org.elasticsearch.client.RestClientBuilder.run(RestClientBuilder.java:187)
	at org.elasticsearch.client.RestClientBuilder.run(RestClientBuilder.java:184)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.elasticsearch.client.RestClientBuilder.build(RestClientBuilder.java:184)
	at org.elasticsearch.client.RestHighLevelClient.<init>(RestHighLevelClient.java:200)
	at org.elasticsearch.client.RestHighLevelClient.<init>(RestHighLevelClient.java:192)
	at com.github.dariobalinzo.elastic.ElasticConnection.createConnectionUsingAuth(ElasticConnection.java:73)
	at com.github.dariobalinzo.elastic.ElasticConnection.<init>(ElasticConnection.java:49)
	at com.github.dariobalinzo.elastic.ElasticConnectionBuilder.build(ElasticConnectionBuilder.java:60)
	at com.github.dariobalinzo.ElasticSourceConnector.start(ElasticSourceConnector.java:85)
	at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:111)
	at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:136)
	at org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:196)
	at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:242)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:908)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access300(DistributedHerder.java:110)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder5.call(DistributedHerder.java:924)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder5.call(DistributedHerder.java:920)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Any idea of this issue? Thank you for advice.

**Comment by DarioBalinzo** [comment]
Hi @sinbadonline,
which version of java and kafka connect are you using?

**Comment by albertwgchu** [comment]
I think I have encountered this as well when using a data set that doesn't have incrementing field name in the entire data set.  In my case it was legacy records that didn't have the incrementing field name.  

To get around this I back filled a value.  However I am wondering with the secondary sort that was added maybe this isn't necessary?
