### ISSUE TITLE
null values

### ISSUE THREAD

**Issue by albertwgchu** [DarioBalinzo/kafka-connect-elasticsearch-source#35]
Hi,

I'm wondering if there's a way to support null values?  We have some documents like this:
{"a": "value", "b":"value"}, {"a":null, "b":"value2"}.  For now I can modify the source to generate  {"b":"value2"}, but I was wondering if there's a different way.

Exception thrown:

[2021-02-24 22:46:40,733] ERROR error (com.github.dariobalinzo.task.ElasticSourceTask)
java.lang.RuntimeException: type not supported XXXX
	at com.github.dariobalinzo.schema.SchemaConverter.convertDocumentSchema(SchemaConverter.java:76)
	at com.github.dariobalinzo.schema.SchemaConverter.convert(SchemaConverter.java:42)
	at com.github.dariobalinzo.task.ElasticSourceTask.parseResult(ElasticSourceTask.java:237)

**Comment by DarioBalinzo** [comment]
Yes, we can add this feature.

So if a field is present into an elastic document, but it is null, what would you like to be the behavior? 
The field should be sent with the null value to kafka or it should be discarded?

**Comment by albertwgchu** [comment]
I think either case would work, I think I would favor sending the null to Kafka though.  Thanks.

**Comment by DarioBalinzo** [comment]
The connector schema api doesn't allow me to send null values, so I will discard it.

**Comment by DarioBalinzo** [comment]
I've published a new 1.4 pre relase version, related to the open issues. The 1.4.1 branch contains the updated documentation.
The master branch still refer to version 1.3, the version published on the official confluent hub. After some time I will check with the confluent team how to update also their version in the hub to the final 1.4 version.
