### ISSUE TITLE
NumberFormatException  for es.host  while starting Elasticsearch source connector

### ISSUE THREAD

**Issue by sunilmchaudhari** [DarioBalinzo/kafka-connect-elasticsearch-source#44]
Hi
I am getting below error when I start connector. 
Please help on this. Its running but Cant see any desired topic in kafka. 

[2021-05-12 16:30:42,611] INFO ElasticSourceConnectorConfig values: 
	batch.max.rows = 10000
	connection.attempts = 3
	connection.backoff.ms = 10000
	es.host = "myhost.uat.com"
	es.password = "myEspass"
	es.port = "9200"
	es.scheme = http
	es.user = "elastic"
	fieldname_converter = avro
	filters.json_cast = null
	filters.whitelist = null
	incrementing.field.name = "@timestamp_log"
	index.prefix = "my_index-*"
	mode = 
	poll.interval.ms = 5000
	topic.prefix = "myprefix_"
 (com.github.dariobalinzo.ElasticSourceConnectorConfig:347)
[2021-05-12 16:30:42,611] ERROR WorkerConnector{id=elasticsearch-source} Error while starting connector (org.apache.kafka.connect.runtime.WorkerConnector:119)
java.lang.NumberFormatException: For input string: ""9200""
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:638)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at com.github.dariobalinzo.ElasticSourceConnector.start(ElasticSourceConnector.java:63)
	at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:111)
	at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:136)
	at org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:196)
	at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:253)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.startConnector(StandaloneHerder.java:293)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:209)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:115)
[2021-05-12 16:30:42,614] INFO Finished creating connector elasticsearch-source (org.apache.kafka.connect.runtime.Worker:269)
[2021-05-12 16:30:42,615] INFO Skipping update of connector elasticsearch-source since it is not running

**Comment by DarioBalinzo** [comment]
Hi,
please try configuring the port as integer and not as string:
changing
`es.port = "9200"`
to
`es.port = 9200`

**Comment by sunilmchaudhari** [comment]
After changing it to an integre, it gives me below error.
Elasticsearch instance is running well on given host and port and I can connect using CURL. 

Is there any problem of HTTPS/HTTP?   
My Elasticsearch is runnong over HTTPS.  I am using HTTP scheme in connector config because I didnt find any SSL config options in documentation. 

[2021-05-12 19:30:46,241] ERROR error in searching index names (com.github.dariobalinzo.elastic.ElasticRepository:105)
[2021-05-12 19:30:46,242] ERROR Stopping after connector error (org.apache.kafka.connect.cli.ConnectStandalone:121)
java.lang.RuntimeException: java.net.UnknownHostException: "myhost.uat.com": Name or service not known
	at com.github.dariobalinzo.elastic.ElasticRepository.catIndices(ElasticRepository.java:106)
	at com.github.dariobalinzo.ElasticSourceConnector.taskConfigs(ElasticSourceConnector.java:98)
	at org.apache.kafka.connect.runtime.Worker.connectorTaskConfigs(Worker.java:319)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.recomputeTaskConfigs(StandaloneHerder.java:303)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.updateConnectorTasks(StandaloneHerder.java:329)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:214)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:115)
Caused by: java.net.UnknownHostException: "myhost.uat.com": Name or service not known

**Comment by DarioBalinzo** [comment]
If you need to use https you can set this:
`es.scheme = https`

I will document better in the connector documentation

**Comment by sunilmchaudhari** [comment]
Hi,
If I use https,  same error it shows.
Can I debug this with any option?


Regards,
Sunil

**Comment by DarioBalinzo** [comment]
Looking at the description: `UnknownHostException: "myhost.uat.com": Name or service not known` maybe the error is related to dns name resolution? 
Can you connect using curl on the same machine where the connector is deployed?

**Comment by sunilmchaudhari** [comment]
Yes,
As I mentioned before, i can connect using curl from the remote machine
where connect is running.
What are the settings if I want to provide trust store, password and the
TLs protocol?

**Comment by sunilmchaudhari** [comment]
Hi @DarioBalinzo  
I found the problem of UnknonHostExcpetion.
Actually I am using configuration with key value pair separated with '='
It doesnt accept hostname in double quote.  So removing double quote it makes http connection with Elasticsearch.
However, since elasticsearch running on HTTPS, connection get closed and it prints in the log that connetion is closed.
I can see in Elasticsearch logs that request came from remote host and its closed. 

Then I set the  es.scheme=https.   Once I restart, it throws "PKIX path builfing error......... Unbale to find valid certification path"

Of-course it will throw this error because we didnt provide any valid root-ca or truststore.
Is it possible to configure truststore location, password and TLS protocol scheme?


regards,
Sunil.

**Comment by sunilmchaudhari** [comment]
Hi @DarioBalinzo ,
any setting to provide certification paths?

**Comment by DarioBalinzo** [comment]
Hi @sunilmchaudhari ,
for the truststore I think you should look at the general kafka connect config, since they are not related to a single connector. Maybe you can find some info here or in the Kafka/Confluent documentation:
https://docs.confluent.io/platform/current/kafka/authentication_ssl.html#kconnect-long

**Comment by sunilmchaudhari** [comment]
Hi @DarioBalinzo ,
I think I have to ask my question precisely.
I am not talking about the SSL error while connecting to broker.
I am getting SSL error while connecting to Elasticsearch when the source connector makes connection to Elasticsearch, which is running over HTTPS. 
So I am taking about ""es.scheme.  If I use es.scheme-https  then there is no provision to use truststore.

**Comment by DarioBalinzo** [comment]
It is possible to customize the settings related to https using the elasticsearch client.
I think that you need something similar to this: (e.g. the path of a custom truststore)
https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/_encrypted_communication.html

I will try to add this configuration to the connector in few days.

**Comment by nmousouros** [comment]
Hi @DarioBalinzo, 

Any progress on that? We have the option indeed, to set those with the sink connector. ( https://github.com/ibm-messaging/kafka-connect-elastic-sink)

**Comment by DarioBalinzo** [comment]
Hi @nmousouros, 
I was waiting for a confirmation about the feature request.
Thanks for sharing the other connector link, it will help me during the development.

I think that now I can start the development.

**Comment by sunilmchaudhari** [comment]
This is great!
Thanks so much Dario.
