### ISSUE TITLE
Data Exception

### ISSUE THREAD

**Issue by RuMcClu** [DarioBalinzo/kafka-connect-elasticsearch-source#51]
I've been using this repo (thanks again btw) and it worked very well until today when suddenly the console is flooded with this error:

[2021-07-16 14:33:03,515] ERROR error (com.github.dariobalinzo.task.ElasticSourceTask:180)
org.apache.kafka.connect.errors.DataException: Invalid Java object for schema type STRUCT: class java.lang.String for field: "old"
	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:245)
	at org.apache.kafka.connect.data.Struct.put(Struct.java:216)
	at org.apache.kafka.connect.data.Struct.put(Struct.java:203)
	at com.github.dariobalinzo.schema.StructConverter.convertDocumentStruct(StructConverter.java:47)
	at com.github.dariobalinzo.schema.StructConverter.convertListOfObject(StructConverter.java:114)
	at com.github.dariobalinzo.schema.StructConverter.lambda$convertListToAvroArray$0(StructConverter.java:81)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at com.github.dariobalinzo.schema.StructConverter.convertListToAvroArray(StructConverter.java:82)
	at com.github.dariobalinzo.schema.StructConverter.convertDocumentStruct(StructConverter.java:49)
	at com.github.dariobalinzo.schema.StructConverter.convert(StructConverter.java:37)
	at com.github.dariobalinzo.task.ElasticSourceTask.parseResult(ElasticSourceTask.java:214)
	at com.github.dariobalinzo.task.ElasticSourceTask.poll(ElasticSourceTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:289)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:256)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

At first I thought it was just a few badly formatted messages but it seems to be for every single message and my pipeline is not working anymore.

Any thoughts on what the problem could be?

Thanks in advance

**Comment by DarioBalinzo** [comment]
Hi,
I'm happy to hear that!

Regarding your problem, can you check if the `old` field in elasticsearch is either a string or array/complex type?

You can fix this using the whitelist config, or the json cast config (fields are not parsed to fixed types, but they are encoded as json strings)

**Comment by RuMcClu** [comment]
Thanks for your reply. The "old" field was a complex blob as you said. Currently I'm using the whitelist to fix this but since the schema in ES is arbitrary it's a little frustrating. Can I suggest the addition of a blacklist option as well?

**Comment by DarioBalinzo** [comment]
You can already find the blacklist option using one of the latest versions: e.g release1.4.2, here the documentation https://github.com/DarioBalinzo/kafka-connect-elasticsearch-source/tree/1.4.2
