### ISSUE TITLE
connector failing to process empty array, throws error

### ISSUE THREAD

**Issue by gauravmangalick** [DarioBalinzo/kafka-connect-elasticsearch-source#62]
Fails to process below json messages, fails to process statusHistoryRanking:
{
"statusHistory": [
    {
      "date": 2021-10-19,
      "status": "IN PASS"
    }
  ],
"statusHistoryRanking": []
}

Error Message:
ERROR (com.github.dariobalinzo.task.ElasticSourceTask:202) error 
java.lang.RuntimeException: error in converting list: type not supported
	at com.github.dariobalinzo.schema.SchemaConverter.convertListSchema(SchemaConverter.java:127)
	at com.github.dariobalinzo.schema.SchemaConverter.convertDocumentSchema(SchemaConverter.java:70)
	at com.github.dariobalinzo.schema.SchemaConverter.convertMapSchema(SchemaConverter.java:89)
	at com.github.dariobalinzo.schema.SchemaConverter.convertDocumentSchema(SchemaConverter.java:74)
	at com.github.dariobalinzo.schema.SchemaConverter.convert(SchemaConverter.java:42)
	at com.github.dariobalinzo.task.ElasticSourceTask.parseResult(ElasticSourceTask.java:245)
	at com.github.dariobalinzo.task.ElasticSourceTask.poll(ElasticSourceTask.java:192)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:268)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:241)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:182)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:231)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

Solution:
SchemaConverter.convertDocumentSchema: check for head is not null:
                    Object head = ((List<?>) value).get(0);
StructConverter.convertListToAvroArray: check for head is not null:
Object head = value.get(0);

**Comment by DarioBalinzo** [comment]
Hi @gauravmangalick, sorry for the delay, I will work on it in few days and I will update here in the issue.

**Comment by DarioBalinzo** [comment]
I'm not able to reproduce the error, the connector seems to skip the empty array: https://github.com/DarioBalinzo/kafka-connect-elasticsearch-source/commit/ae64214ff095ca1cced043ff5efa014744e78639
