### ISSUE TITLE
Rest client version conflicts when used with confluent elastic search sink connector

### ISSUE THREAD

**Issue by NaveenChandel** [DarioBalinzo/kafka-connect-elasticsearch-source#63]
When using it with elastic search sink connector - https://github.com/confluentinc/kafka-connect-elasticsearch

Facing error:
```
[2021-10-20 17:42:45,631] ERROR Stopping after connector error (org.apache.kafka.connect.cli.ConnectStandalone:121)
java.lang.NoSuchMethodError: 'org.elasticsearch.client.Response org.elasticsearch.client.RestClient.performRequest(java.lang.String, java.lang.String, org.apache.http.Header[])'
        at com.github.dariobalinzo.elastic.ElasticRepository.catIndices(ElasticRepository.java:103)
        at com.github.dariobalinzo.ElasticSourceConnector.taskConfigs(ElasticSourceConnector.java:98)
        at org.apache.kafka.connect.runtime.Worker.connectorTaskConfigs(Worker.java:323)
        at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.recomputeTaskConfigs(StandaloneHerder.java:305)
        at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.updateConnectorTasks(StandaloneHerder.java:331)
        at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:216)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:115)
```

I think this is due to version mismatch b/w both connectors dependency - as the RestClient have been changed in both versions.
```
        <dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>elasticsearch-rest-high-level-client</artifactId>
            <version>6.2.3</version>
        </dependency>
```
and 
```
        <dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>elasticsearch-rest-high-level-client</artifactId>
            <version>7.9.3</version>
        </dependency>
```

Can we update this dependency?

**Comment by NaveenChandel** [comment]
@DarioBalinzo Any thoughts on this?

**Comment by DarioBalinzo** [comment]
I will try to update the dependency as suggested soon. I tried in the past to switch to version 7.x but i had a classpath problem in past running the connector. 

However I will retry it with your suggested version

**Comment by albertwgchu** [comment]
Note I am using Confluent Elasticsearch sink 5.5.3 (the most recent version when I started my project) and things work fine.

**Comment by NaveenChandel** [comment]
@albertwgchu Didn't try with that version. I was trying the latest version 11.1.0. I guess they state in the docs,

"As of version 11.0.0, the connector uses the Elasticsearch High Level REST Client (version 7.0.1), which means only Elasticsearch 7.x is supported"

As I'm working with elastic search 7.6.1 had just gone ahead with the latest.
