### ISSUE TITLE
Entity content too long: com.github.dariobalinzo.task.ElasticSourceTask:202

### ISSUE THREAD

**Issue by cabexius** [DarioBalinzo/kafka-connect-elasticsearch-source#68]
How to set a configuration....

to avoid this error, noted the fact the has defaulted this to 100mb (https://github.com/elastic/elasticsearch/blob/master/client/rest/src/main/java/org/elasticsearch/client/HttpAsyncResponseConsumerFactory.java)

(com.github.dariobalinzo.task.ElasticSourceTask:202)
org.apache.http.ContentTooLongException: entity content is too long [167942814] for the configured buffer limit [104857600]
       at org.elasticsearch.client.HeapBufferedAsyncResponseConsumer.onEntityEnclosed(HeapBufferedAsyncResponseConsumer.java:76)
       at org.apache.http.nio.protocol.AbstractAsyncResponseConsumer.responseReceived(AbstractAsyncResponseConsumer.java:131)
       
   tried lowering configuration:
    "batch.max.rows": 1000,
    
    but still hitting the error?
    
    help! idea!  thanks

**Comment by cabexius** [comment]
"batch.max.rows": works as coded, if one receives error above, just make sure to keep lowering your batch.max.rows until it works.
;) start with "batch.max.rows": 1, the work yourself up. thanks great work!!!
