### ISSUE TITLE
missing build flavor oss

### ISSUE THREAD

**Issue by gitshrl** [DarioBalinzo/kafka-connect-elasticsearch-source#69]
We are getting an error missing build flavor oss when trying to connect to ES 7.2, but no issue in ES 7.2 build_falvor default.

[2022-03-24 16:49:06,640] ERROR error (com.github.dariobalinzo.task.ElasticSourceTask:217)
ElasticsearchException[Invalid or missing build flavor [oss]]
        at org.elasticsearch.client.RestHighLevelClient.performClientRequest(RestHighLevelClient.java:2701)
        at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:2171)
        at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:2137)
        at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:2105)
        at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1367)
        at com.github.dariobalinzo.elastic.ElasticRepository.executeSearch(ElasticRepository.java:176)
        at com.github.dariobalinzo.elastic.ElasticRepository.searchAfter(ElasticRepository.java:90)
        at com.github.dariobalinzo.task.ElasticSourceTask.poll(ElasticSourceTask.java:205)
        at org.apache.kafka.connect.runtime.Wor

**Comment by gitshrl** [comment]
Solved by downgrading elasticsearch-rest-high-level-client & elasticsearch-rest-client version to 7.2

https://github.com/gitshrl/kafka-connect-elasticsearch-source
